name: edit_map_example
description: Demonstrates how to use the edit_map plugin.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  edit_map:
    path: ../
  dio: ^4.0.4
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0