name: edit_map
description: The map which allows your users to interact with 2D objects.
homepage: https://pub.dev/packages/edit_map
repository: https://github.com/arrrtem22/edit_map/
issue_tracker: https://github.com/arrrtem22/edit_map/issues
version: 0.0.3

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

environment:
  sdk: '>=2.19.0-0 <4.0.0'
  flutter: ">=2.5.0"